name: LegendCraft
version: 0.11.2
depend: [WorldEdit]
softdepend: [Multiverse-Core]
main: me.plasmarob.legendcraft.LegendCraft
description: LoZ / AdventureCraft plugin
commands:
  lc:
    description: main command. Type /lc help for more.
  lca:
    description: /lc add. Type /lc help for more.
  lce:
    description: /lc edit. Type /lc help for more.
  legendCraft:
    description: main command. Type /lc help for more.
